services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /
    disk:
      name: telegram-bot-disk
      mountPath: /opt/render/project/src
      sizeGB: 1